utils::globalVariables(c("aes", ".fitted", ".resid", "geom_point", ".stdresid",
                       "geom_hline", "xlab", "ylab", "ggtitle", "stat_smooth",
                       "geom_abline", ".cooksd", "geom_bar", ".hat", "theme",
                       "scale_size_continuous", "z", "ord.x", "geom_point",
                       "geom_ribbon", "lower", "upper", "geom_text", "label",
                       "cens", "surv", "geom_step", "up", "low", "theme_bw",
                       "group", "scale_colour_manual", "scale_colour_discrete",
                       "scale_linetype_manual"))

#' Quantile-Quantile Plots with ggplot2
#'
#' Produce standard quantile-quantile plots for modeling using ggplot2.
#'
#' @param x A numeric vector of residuals from a generalized linear model.
#' @param distribution The reference probability distribution for residuals.
#'
#' @importFrom ggplot2 ggplot
#'
#' @export qqPlot_gg
#'
#' @examples
#' n <- 10; x1 <- rnorm(n); y1 <- rnorm(n)
#' linmod <- lm(y1 ~ x1)
#' x <- linmod$residuals
#' qqPlot_gg(x)

qqPlot_gg <- function(x, distribution = "norm", ..., line.estimate = NULL,
                      conf = 0.95, labels = names(x)) {
  q.function <- eval(parse(text = paste0("q", distribution)))
  d.function <- eval(parse(text = paste0("d", distribution)))
  x <- na.omit(x)
  ord <- order(x)
  n <- length(x)
  P <- ppoints(length(x))
  df <- data.frame(ord.x = x[ord], z = q.function(P, ...))

  if(is.null(line.estimate)) {
    Q.x <- quantile(df$ord.x, c(0.25, 0.75))
    Q.z <- q.function(c(0.25, 0.75), ...)
    b <- (diff(Q.x) / diff(Q.z))
    coef <- c(Q.x[1] - b * Q.z[1], b)
  } else {
    coef <- coef(line.estimate(ord.x ~ z))
  }

  zz <- qnorm(1 - ( (1 - conf) / 2))
  SE <- (coef[2] / d.function(df$z)) * sqrt(P * ( (1 - P) / n))
  fit.value <- coef[1] + coef[2] * df$z
  df$upper <- fit.value + zz * SE
  df$lower <- fit.value - zz * SE

  if(!is.null(labels)) {
    df$label <- ifelse(df$ord.x > df$upper | df$ord.x < df$lower, labels[ord], "")
  }

  p <- ggplot(df, aes(x = z, y = ord.x)) +
    geom_point() +
    geom_abline(intercept = coef[1], slope = coef[2]) +
    geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.2) +
    ylab("Model Residual Quantiles") + xlab("Theoretical Quantiles") +
    ggtitle("Quantile Plot Residuals")
  if(!is.null(labels)) {
    p <- p + geom_text( aes(label = label))
  }
  return(p)
}


#' Linear Model Diagnostic Plots with ggplot2
#'
#' Produce standard diagnostic plots for linear models using ggplot2.
#'
#' @param model A linear model object produced by \code{lm()}.
#'
#' @importFrom ggplot2 ggplot
#' @importFrom gridExtra grid.arrange
#'
#' @export lmPlots_gg
#'
#' @examples
#' n <- 10; x1 <- rnorm(n); y1 <- rnorm(n)
#' linmod <- lm(y1 ~ x1)
#' lmPlots_gg(linmod)

lmPlots_gg <- function(model) {
  p1 <- ggplot(model, aes(.fitted, .resid)) + geom_point()
  p1 <- p1 + stat_smooth(method = "loess") +
             geom_hline(yintercept = 0, col = "red", linetype = "dashed")
  p1 <- p1 + xlab("Fitted values") + ylab("Residuals") +
             ggtitle("Residual vs. Fitted")

  p2 <- ggplot(model,aes(sample=.stdresid)) + geom_point(stat = "qq") +
        geom_abline() + xlab("Theoretical Quantiles") + ylab("Std. Residuals") +
        ggtitle("Gausian Q-Q")

  p3 <- ggplot(model, aes(.fitted, sqrt(abs(.stdresid)))) +
        geom_point(na.rm = TRUE)
  p3 <- p3 + stat_smooth(method = "loess", na.rm = TRUE) + xlab("Fitted Value")
  p3 <- p3 + ylab(expression(sqrt("|Std. residuals|")))
  p3 <- p3 + ggtitle("Scale-Location")

  p4 <- ggplot(model, aes(seq_along(.cooksd), .cooksd)) +
        geom_bar(stat = "identity", position = "identity")
  p4 <- p4 + xlab("Obs. No.") + ylab("Cook's distance")
  p4 <- p4 + ggtitle("Cook's distance")

  p5 <- ggplot(model, aes(.hat, .stdresid)) +
        geom_point(aes(size = .cooksd), na.rm = TRUE)
  p5 <- p5 + stat_smooth(method = "loess", na.rm = TRUE) + xlab("Leverage") +
             ggtitle("Resid. vs Leverage") + ylab("Std. Resid.")
  p5 <- p5 + scale_size_continuous("Cook's Distance", range = c(1,5))
  p5 <- p5 + theme(legend.position = "none")

  p6 <- ggplot(model, aes(.hat, .cooksd)) + geom_point(na.rm = TRUE) +
        stat_smooth(method = "loess", na.rm = TRUE) + xlab("Leverage") +
        ylab("Cook's Distance") + ggtitle("Cook's dist. vs. Lev.") +
        geom_abline(slope = seq(0,3,0.5), color = "gray", linetype = "dashed")

  return(grid.arrange(p1, p2, p3, p4, p5, p6, nrow = 2, ncol = 3))
}


#' Kaplan-Meier Plot with ggplot2
#'
#' Produce a survival plot of a Kaplan-Meier estimator using ggplot2.
#'
#' @param s Survival model object, generated by methods like Kaplan-Meier.
#' @param CI Type of confidence interval for the survival object.
#' @param surv.col Color for observations with outcomes of "survived".
#' @param cens.col Color for observations with outcomes of "censored".
#' @param back.white Boolean for desired background color in plots.
#' @param xlab A label for the x-axis, defaults to "Time".
#' @param ylab A label for the y-axis, defaults to "Survival".
#' @param main A main label for the survival plot, no default.
#'
#' @importFrom ggplot2 ggplot
#' @importFrom survival survfit Surv
#'
#' @export survPlot_gg
#'
#' @examples
#' hmohiv <- read.table("http://www.ats.ucla.edu/stat/r/examples/asa/hmohiv.csv", sep=",", header = TRUE)
#' mini <- hmohiv[ID <= 5, ]
#' s <- survfit(Surv(mini$time, mini$censor) ~ 1)
#' survPlot_gg(s)

survPlot_gg <- function(s, CI = "def", plot.cens = TRUE, surv.col = "gg.def",
                        cens.col = "red", lty.est = 1, lty.ci = 2,
                        cens.shape = 3, back.white = FALSE, xlab = "Time",
                        ylab = "Survival", main = "") {

  strata <- ifelse(is.null(s$strata) == TRUE, 1, length(s$strata))
  stopifnot(length(surv.col) == 1 | length(surv.col) == strata)
  stopifnot(length(lty.est) == 1 | length(lty.est) == strata)

  ggsurv.s <- function(s, CI = "def", plot.cens = TRUE, surv.col = "gg.def",
                       cens.col = "red", lty.est = 1, lty.ci = 2,
                       cens.shape = 3, back.white = FALSE, xlab = "Time",
                       ylab = "Survival", main = ""){

    dat <- data.frame(time = c(0, s$time), surv = c(1, s$surv),
                      up = c(1, s$upper), low = c(1, s$lower),
                      cens = c(0, s$n.censor))
    dat.cens <- subset(dat, cens != 0)

    col <- ifelse(surv.col == "gg.def", "black", surv.col)

    pl <- ggplot(dat, aes(x = time, y = surv)) + xlab(xlab) + ylab(ylab) +
          ggtitle(main) + geom_step(col = col, lty = lty.est)

    pl <- if(CI == TRUE | CI == "def") {
      pl + geom_step(aes(y = up), color = col, lty = lty.ci) +
        geom_step(aes(y = low), color = col, lty = lty.ci)
    } else (pl)

    pl <- if(plot.cens == TRUE & length(dat.cens) > 0) {
      pl + geom_point(data = dat.cens, aes(y = surv), shape = cens.shape,
                      col = cens.col)
    } else if (plot.cens == TRUE & length(dat.cens) == 0) {
      stop ("There are no censored observations")
    } else (pl)

    pl <- if(back.white == TRUE) {
      pl + theme_bw()
    } else (pl)
    pl
  }

  ggsurv.m <- function(s, CI = "def", plot.cens = TRUE, surv.col = "gg.def",
                       cens.col = "red", lty.est = 1, lty.ci = 2,
                       cens.shape = 3, back.white = FALSE, xlab = "Time",
                       ylab = "Survival Probability", main = "") {
    n <- s$strata
    groups <- factor(unlist(strsplit(names(s$strata), "="))[seq(2, 2 * strata,
                                                                by = 2)])
    gr.name <-  unlist(strsplit(names(s$strata), "="))[1]
    gr.df <- vector("list", strata)
    ind <- vector("list", strata)
    n.ind <- c(0,n); n.ind <- cumsum(n.ind)
    for (i in 1:strata) ind[[i]] <- (n.ind[i] + 1):n.ind[i + 1]

    for (i in 1:strata) {
      gr.df[[i]] <- data.frame(
        time = c(0, s$time[ ind[[i]] ]),
        surv = c(1, s$surv[ ind[[i]] ]),
        up = c(1, s$upper[ ind[[i]] ]),
        low = c(1, s$lower[ ind[[i]] ]),
        cens = c(0, s$n.censor[ ind[[i]] ]),
        group = rep(groups[i], n[i] + 1))
    }

    dat <- do.call(rbind, gr.df)
    dat.cens <- subset(dat, cens != 0)

    pl <- ggplot(dat, aes(x = time, y = surv, group = group)) +
      xlab(xlab) + ylab(ylab) + ggtitle(main) +
      geom_step(aes(col = group, lty = group))

    col <- if(length(surv.col == 1)) {
      scale_colour_manual(name = gr.name, values = rep(surv.col, strata))
    } else{
        scale_colour_manual(name = gr.name, values = surv.col)
    }

    pl <- if(surv.col[1] != "gg.def") {
      pl + col
    } else {
        pl + scale_colour_discrete(name = gr.name)
    }

    line <- if(length(lty.est) == 1) {
      scale_linetype_manual(name = gr.name, values = rep(lty.est, strata))
    } else {
        scale_linetype_manual(name = gr.name, values = lty.est)
    }

    pl <- pl + line

    pl <- if(CI == TRUE) {
      if(length(surv.col) > 1 && length(lty.est) > 1){
        stop('Either surv.col or lty.est should be of length 1 in order
             to plot 95% CI with multiple strata')
      } else if((length(surv.col) > 1 | surv.col == 'gg.def')[1]) {
        pl + geom_step(aes(y = up, color = group), lty = lty.ci) +
          geom_step(aes(y = low, color = group), lty = lty.ci)
      } else {
          pl +  geom_step(aes(y = up, lty = group), col = surv.col) +
          geom_step(aes(y = low,lty = group), col = surv.col)
        }
    } else (pl)

    pl <- if(plot.cens == TRUE & length(dat.cens) > 0) {
      pl + geom_point(data = dat.cens, aes(y = surv), shape = cens.shape,
                      col = cens.col)
    } else if (plot.cens == TRUE & length(dat.cens) == 0) {
      stop ("There are no censored observations")
    } else (pl)

    pl <- if(back.white == TRUE) {pl + theme_bw()
    } else (pl)
    pl
  }
  pl <- if(strata == 1) {
          ggsurv.s(s, CI , plot.cens, surv.col , cens.col, lty.est, lty.ci,
                   cens.shape, back.white, xlab, ylab, main)
  } else {
      ggsurv.m(s, CI, plot.cens, surv.col , cens.col, lty.est, lty.ci,
               cens.shape, back.white, xlab, ylab, main)
         }
  return(pl)
}
